### ISSUE TITLE
Standard resource description doc 

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/WorkingGroups#10]

**Comment by jordonezlucena** [comment]
Not sure who is the owner of this issue, and what is expected here.

**Comment by jordonezlucena** [comment]
No contribution yet. No clue on the expected outcome of this issue. Could anyone clarify on this?

**Comment by shilpa-padgaonkar** [comment]
Hope this helps clarify the issue:

- This was a contribution recommended by Microsoft, "To document the common vocabulary and terminologies used across API families" (possibly resembling a glossary?) See the MOM notes here https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/MeetingMinutes/MOM-2021-11-10.md

- This was later again requested by E/// :- https://github.com/camaraproject/WorkingGroups/issues/18

No update on contributions yet.

**Comment by jordonezlucena** [comment]
Some API related terminology/concept can be fetched from the general principles doc (issue #32). 
Other concepts that we should capture in the document is what test case, test campaigns, mean in the context of CAMARA.

**Comment by shilpa-padgaonkar** [comment]
An empty template called Glossary.md will be added. Any terms not covered as a part of the general principles doc can be covered here.
