### ISSUE TITLE
The referred link seems not existed.

### ISSUE THREAD

**Issue by zhenqidong** [camaraproject/WorkingGroups#100]
The link pointing to https://www.3gpp.org/common-api-framework-capif in the document at (https://github.com/camaraproject/WorkingGroups/tree/main/Commonalities/documentation)/CAMARA-AuthN-AuthZ-Concept.md seems broken.

**Comment by shilpa-padgaonkar** [comment]
@zhenqidong : Please check https://github.com/camaraproject/WorkingGroups/pull/107

**Comment by shilpa-padgaonkar** [comment]
Closing issue after merging https://github.com/camaraproject/WorkingGroups/pull/107
