### ISSUE TITLE
CAMARA API target pattern

### ISSUE THREAD

**Issue by DT-DawidWroblewski** [camaraproject/WorkingGroups#105]
Dear CAMARA team!

I want to rise an issue regarding API pattern for CAMARA.

At this moment API pattern for CAMARA is that products are being served on dedicated endpoints, e.g.:

*"/dscp"* for Home Devices QoD

from SW developer perspective it means a new endpoint has to be maintained for every new/additional CAMARA API.

In Mobile Connect we differentiate API services based on a value that comes with *"scope"* parameter.

For developers it means that only 3 endpoints are maintained:

1. /authorize
2. /token
3. /userinfo

If API service requests any specific parameters, e.g. some sophisticated identifier or object (JSON), these can be passed inside userinfo request BODY.

This approach is valuable from developer's perspective since she/he can use OpenID Connect/OAUTH library to handle the flow (e.g. Nimbus) and only play with ***"scope"*** value that triggers a certain business logic on MNO side that delivers desired service on userinfo.

*Examples*:

scope: dscp => ***dscp*** userInfo response

scope: mc_atp_boolean => ***mc_atp_boolean*** userInfo response

etc.

For MNO it simplifies deployment as northbound we expose 3 endpoints (based on OpenID Connect/OAUTH standards) and the only thing that requires adoption/SW dev is business logic.

This approach is proven to work, as Mobile Connect APIs works this way and this pattern is backed by GSMA and MNO community.

This topic came out during initial discussions we had on simSwap API. However, it addresses the CAMARA API architecture design, therefore it is worth discussing it now and adopting changes to APIs if we agree to change API pattern.

**Comment by patrice-conil** [comment]
Hi @DT-DawidWroblewski,
IMHO  such an approach only facilitates deployment and not consumption. If we want to make it easier to adopt/consume our API, we need to think as an API consumer and not as an API provider.
How to clearly describe a response that depends on the scope? As an API consumer, I like the self-described API via openapi specs. If I need to read additional documentation to understand how an API works... there's a lot of chance that I'll choose another one that does the job and is easier to understand.

Patrice

**Comment by DT-DawidWroblewski** [comment]
As an API consumer you can get a Swagger that describes API consumption based on scopes :) 

Please find MC APIs yaml files in ZIP attached

[MCAPIs(yaml).zip](https://github.com/camaraproject/WorkingGroups/files/9961950/MCAPIs.yaml.zip)

**Comment by DT-DawidWroblewski** [comment]
Hi Eric!

Thanks for the feedback - highly appreciated :)

I agree that when you think of "outside End-User context" *basePath* approach is easier, although it depends on what is API nature & how you design it, e.g. when API is designed in a way, where a response can be obtained by calling endpoint like:

*someSuperMno.com/developer/api/v1/location/msisdn/48602602602*

it is not friendly at all :P (consider using this pattern for millions of MSISDNs)

If you have End-User context in the flow, it is recommended to protect your resource e.g. by using **OpenID Connect** or **OAUTH2.0**. Therefore, start with authenticating the user, then getting tokens, and in the end calling resources using an access token.

Knowing that the Mobile Connect community developed several methods to call MC APIs with or without the user context:
1. Mobile Connect Device Initiated OIDC Profile
2. Mobile Connect Server Initiated OIDC Profile (*CIBA Notification* + *CIBA Pooling*)
3. Mobile Connect Client Credentials Profile (*MC CC*) => **without user context**

The main API differentiator in MC APIs is ***scope***.

For *MC CC*, MNO community, under GSMA assumptions, specified the following approach to handle identifiers:

> **Resource Request**
>
> The resource request MUST be performed as indicated in the corresponding MC attribute service specification (e.g. MC ATP [7]).
However, given that the access tokens delivered by MC Client Credentials are generic, a new mechanism is defined to indicate the MC User whose data is being queried in the request. Namely, the following HTTP headers MUST be used for that purpose:


|HTTP Header|Usage Category|Description|
|:---|:---:|:---|
|User-ID-Type|**REQUIRED** [if the bearer type access token provided in the request is generic]|MC User identification type used in the *User-ID* header. One of these values MUST be used: +***MSISDN***: Indicates the User-ID contains a plain MSISDN in international format according to ITU-T recommendation E.164 [11]. The plus sign (+) MUST NOT be included as a prefix. +***ENCR_MSISDN***: Indicates the User-ID contains an encrypted MSISDN as specified for the login_hint parameter in the Device-Initiated and Server-Initiated flows. See MC Technical Architecture and Core Requirements [2] for details. Support for the MSISDN user ID type is REQUIRED, whereas for ENCR_MSISDN is OPTIONAL.|
|User-ID|REQUIRED [if the bearer type access token provided in the request is generic]|MC User identification value as per the type indicated in the HTTP header above.|

(Ref.: ***MC Client Credentials for Attributes – Local Specification for Spain 2019, Version 1.0
16 January 2020, Created by GSMA, Orange, Telefonica and Vodafone for the Spanish market***)

> it is possible to add some flavors here, e.g. have ***User-ID-Type***: ***IP*** and pass IP address inside ***User-ID*** header)

MC Specs works commercially on several markets. *MC CC* Originally developed in ***UK*** & **Spain** (Orange, Telefonica, Vodafone), then was adopted by MNOs in **Germany** (DT, Telefonica, Vodafone), **Netherlands** (and countries where DT operates).

MC Specs took into consideration the developer perspective as well as various End-User contexts. Therefore MC standard aims to API flow, as there are only 2 (or 3, if device involvement is required - *Number Verify*) endpoints. However, MNO has all the business logic **under the hood** and needs to create good documentation for developers.

In a previous message I passed swaggers inside ZIP file, that covers *the user context*. Additionally, please find a sample that is used for Mobile Connect Account Takeover Protection (simSwap) that works outside the user context.

[CAMARA_simSwap.zip](https://github.com/camaraproject/WorkingGroups/files/9979426/CAMARA_simSwap.zip)

**Comment by bigludo7** [comment]
Hello,
@DT-DawidWroblewski  I see 2 distinct topic in your post:

1. API pattern with a generic api (and a scope attribute to allow API customer to specify the request) vs specific api resource per business requirement (as we have crafted so far)
2. Input criteria that can be passed in post body or in HTTP header

This 2 topics could be tackled independently correct ?
For me we can apply a pattern with specific api resource per  business requirement.

As you share a proposal for a Camara simswap with a scope and generic end-point, I share a swagger sample with specific operation for the simswap (aligned with current pattern used for all api). This will allow the team to get a swagger for both flavor and assess pro & con.
I tend to think that it is a priority point to solve as we have development in progress.

Thanks

[checkSimSwap-v0.3.0.camara.swagger.yaml.zip](https://github.com/camaraproject/WorkingGroups/files/9980007/checkSimSwap-v0.3.0.camara.swagger.yaml.zip)

**Comment by eric-murray** [comment]
@DT-DawidWroblewski 
Well, I certainly agree with you on path parameters. Definitely to be avoided for network APIs!

I think this discussion is related to the UE identification (#101) and user consent (#60) issues and the specific Telefonica proposals on these issues. I agree that if so much of the request context has to be specified just to get issued the OAuth token, then it doesn't make sense to have to repeat all that context for the actual request itself.

But I don't believe the Telefonica proposals capture all the possible use cases for CAMARA APIs, particularly for "low budget" API users who do not have the support or IT systems or even requirement to streamline their applications to make millions of highly optimised calls. Perhaps you could contribute to those issues, and see what design patterns this leads to when these issues have been resolved.

**Comment by RubenBG7** [comment]
Hi Guys,
IMO Scopes should be used to authorize consumers to execute endpoints and securize them one by one. Of course, use this kind of flows could be easier for some consumers, but we are avoding optIn Control, params control.... in summary we are avoiding the strongly description and use of APIs, making them open to interpret usability

**Comment by trehman-gsma** [comment]
All,

(I also apologize for joining this discussion late)

I've recently joined GSMA as an API resource and am keen to contribute to CAMARA.

I do agree with the general consensus about using dedicated endpoints. I feel that dedicated endpoints are easier for API consumers (for all the reasons mentioned above) but also that they are easier for API providers to develop against. From my development perspective, dedicated endpoints offer some of the following efficiencies:
- They comply with single-responsibility principle and separation of concerns principle, both of which are encouraged by many programming/design paradigms. 
- Require less maintenance when a new requirement is introduced (shared resources will be impacted by all requirement changes whereas dedicated resources are impacted by only the requirements in their context).
- Easier to test against (unit tests and integration tests are isolated and therefore faster to implement)
- Smaller vector for defects 
- Cleaner code and clearer internal governance
