### ISSUE TITLE
Avoid telco specific terminology in APIs

### ISSUE THREAD

**Issue by RandyLevensalor** [camaraproject/WorkingGroups#108]
There appears to be a preference to using mobile / 3GPP specific terminology for the APIs.  This makes it confusing for adding wireline networks.  Plus API consumers may not be familiar with 3GPP terminology.

One example is using UE to describe a user device.  This is included in the [commonalities documentation](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/UE-Identification.md) and the [QualityOnDemand API](https://github.com/camaraproject/QualityOnDemand/blob/main/code/API_definitions/qod-api.yaml).

Moving to something access network independent could improve the clarity of the APIs for the API consumers and wireline providers.   Instead of UE, we could use device, user device, or target device for managing the local device.  This would also preclude a SIM as a part of the northbound APIs.

**Comment by shilpa-padgaonkar** [comment]
@RandyLevensalor https://github.com/camaraproject/WorkingGroups/pull/120 has been created to address the issue. You are welcome to contribute.

**Comment by shilpa-padgaonkar** [comment]
As there are individual issues for subproject created, this issue will be closed
