### ISSUE TITLE
API doc template review

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/WorkingGroups#11]
Kindly review the first draft for api documentation template.

**Comment by T-sm** [comment]
Template moved to https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Deliverables/API-DocumentationTemplate.md

**Comment by Kevsy** [comment]
Created [Pull Request 23](https://github.com/camaraproject/WorkingGroups/pull/23) with two additions:
1- added 'ability to execute samples directly from the documentation Web page (as per Open API)' to 'Code Snippets'
2 - created 'Policies' sub-section, for discovery of additional policies beyond authentication/authorisation.

**Comment by T-sm** [comment]
The PR has been discussed during the Commonalities calls and no objections were raised. The additions have been incorporated into the document.

**Comment by T-sm** [comment]
Thank you for your reviews, since there are no further comments this issue will be closed as agreed during our last _Commonalities Workgroup_ meeting.
