### ISSUE TITLE
Developer Certificate of Origin

### ISSUE THREAD

**Issue by FabrizioMoggio** [camaraproject/WorkingGroups#119]
The DCO is achieved adding  **Signed-off-by: <real name> <email>** in the Commit. I'm wondering if, when the contribution is on behalf of an external entity, such as GSMA, it could be more appropriate to also add some further comment and also adding the names and email addresses of the other external contributors. For example:

Contribution from GSMA, Signed-off-by: Fabrizio Moggio <fabrizio.moggio@telecomitala.it)>, on behalf of Deepak Gunjal <deepak.a.gunjal@capgemini.com> etc

Considering the Project Charter and intellectual-property-policy section, we also have: 

"All new inbound contributions of Project Materials must also be accompanied by a Developer Certificate of Origin sign-off in the source code system that is submitted through a **Steering Committee approved contribution process** which will bind the authorized contributor and, if not self-employed, their employer to the applicable license;"

Is the SC Process just related to the production of the contribution from a group that works under Apache 2.0 or something more is needed?

**Comment by shilpa-padgaonkar** [comment]
@FabrizioMoggio : From my point of view, the usual git way is to set the username, email(official) with git config and then do a signoff using -s flag and this should typically suffice.

However, to check if there are specific requirements when it comes to organizations like GSMA and if there was anything additional agreed as a part of the SC approved contribution process, I would request @MarkusKuemmerle to provide the details.

**Comment by MarkusKuemmerle** [comment]
There are no specific requirements, we're only following the open source standards. So let's do it according the way Shilpa proposed

**Comment by FabrizioMoggio** [comment]
**Conclusion:** for a contribution from an external organization, like GSMA, we can proceed with the signature from the publisher only. It is anyway possible to add in the "Commit comment" any further reference from the originating organization. This is not formalized or required, it is up to the publisher.

I think that the conclusion is fine, I would anyway request @MarkCornall, @tomvanpelt a comment on the above conclusion.

**Comment by shilpa-padgaonkar** [comment]
@FabrizioMoggio : Can we close this issue?

**Comment by FabrizioMoggio** [comment]
**Conclusion**: for a contribution from an external organization, like GSMA, we can proceed with the signature from the publisher only. It is anyway possible to add in the "Commit comment" any further reference from the originating organization. This is not formalized or required, it is up to the publisher
