### ISSUE TITLE
Change for APIBacklog

### ISSUE THREAD

**Issue by MarkusKuemmerle** [camaraproject/WorkingGroups#12]
Ericsson proposed the changes in this PDF: https://github.com/camaraproject/WorkingGroups/blob/main/APIBacklog/documentation/Contributions/API%20backlog%20proposal%20for%20change.pdf

**Comment by jordonezlucena** [comment]
- Has a document been re-submitted to address the above comments?
- GSMA's OPAG is going to provide a new backlog (to re-define prioritizations) shortly, as long as ToR between OPAG and CAMARA is officially agreed (one minor point still pending)

**Comment by ToshiWakayama-KDDI** [comment]
Here is KDDI comment: 
Page 2:  Network slicing or Connectivity Service management & monitoring, whatever name would be fine with us, but Network slicing is one of the important topics for Telco, so, this API family should be prioritised.  KDDI is interested in it, so please add KDDI to Contributors, if ok.

**Comment by jordonezlucena** [comment]
A live table will be generated to record all proposals, following the template captured in the guidelines to be approval on the next SteerCo call (8th Sept). Action will be taken upon approving these guidelines.
