### ISSUE TITLE
Reference Architectures

### ISSUE THREAD

**Issue by jordonezlucena** [camaraproject/WorkingGroups#13]
This issue is to check if the team agrees on the architecture(s) to be used as a reference. The initial proposal is to use the (1) ITU-T Cloud Reference Architecture; and 2) TMF Network as a Service framework. 
We do not pretend to include architecture work of the project (that we understand should be focusing on developing the APIs) but to **understand (and hopefully agree) on the context for such APIs**, helping operators and technology providers that may be willing to include these APIs in their products. 

The attached PPT provides a quick overview of the reference architectures, and presents a proposal for linking the different API families with them. We'd like to know the view of the rest of participants. 
[Reference Architectures.pptx](https://github.com/telekom/telco-global-api-alliance/files/7065771/Reference.Architectures.pptx)

**Comment by jordonezlucena** [comment]
No further comments received. 
PPT moved to the /Commonalities/documentation/Deliverables directory -> https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Deliverables/Reference.Architectures.pptx

**Comment by jordonezlucena** [comment]
Should we close this issue, or should we keep it alive for the entire project? I prefer the first option, and when/if needed, then we can re-open the issue.

**Comment by T-sm** [comment]
Thank you for your input! Closing this issue as agreed during May 4th Commonalities Workgroup meeting.
