### ISSUE TITLE
Create issue and pr templates

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/WorkingGroups#163]
Issue templates are helpful when we want to provide guidance for opening issues while allowing contributors to specify the content of their issues. 
Similarly PR templates help to describe and categorise the pull request better. It also helps creating better release documentation for sub-projects.

With this issue, we intend to create PR which will decide on a common issue and pr template that can be used across sub-projects. The intention is to follow best practises specified in the github documentation as well as use the issue and pr templates provided by project like K8s as reference for eg. https://github.com/kubernetes/kubernetes/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by RubenBG7** [comment]
Reviewed and ok gave from TEF side.

**Comment by eric-murray** [comment]
Yes, happy, and already using it
