### ISSUE TITLE
Revisit API documentation template to reduce redundancy

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/WorkingGroups#164]
Currently, a lot of information for the API spec file is duplicated in the API documentation. This results in huge efforts even when making very small, insignificant changes to the API as we need to duplicate the information back to the API documentation. 
With this issue, the suggestion is to have no/very minimum redundant information as a part of the API documentation that is already a part of the spec file.

**Comment by jordonezlucena** [comment]
Hi Shilpa, any concrete proposal to move discussion forward?

**Comment by shilpa-padgaonkar** [comment]
@jordonezlucena : 
I would propose to not have the errors section in the doc. This is already a part of the spec file
Also, for the endpoint definition section, we should only include the things which are not already a part of the spec. 
The intention is to have the spec file as the main source of truth and the document is more supplementary for eg. to provide FAQs, general overview, code snippets etc.

**Comment by shilpa-padgaonkar** [comment]
Approach seems to be ok. We need to provide a sample api spec which is more complete as part of this issue/pr to set an example.

**Comment by eric-murray** [comment]
My proposal would be not to have separate documentation at all, but to embed all documentation within the OAS (Swagger) definition itself. The Swagger Editor (an open source project) can then be used as the "documentation viewer". Sub projects can add as much or as little additional documentation within the OAS definition file as preferred without the overhead of needing to update separate documentation when the OAS definition is updated.

The Swagger editor appears to render both markdown and HTML are supported to some extent, though doesn't appear very well documented what exactly is supported, so might need some trial an error. Images and other external documents can be inline linked with a bit of patience.

**Comment by shilpa-padgaonkar** [comment]
Even better! I suggested a mellow approach to start with expecting it might not go down that well :)

**Comment by shilpa-padgaonkar** [comment]
As discussed in the commonalities meeting, at least 2 subprojects can nominate themselves to provide the improved version of their spec files as showcases

**Comment by shilpa-padgaonkar** [comment]
If we have no nominations until the commonalities call on Thurday 23rd Mar, we might have to restrict the scope of this issue to updating the API documentation template. The template will include a new comment under sections Errors and Endpoints that this information should be a part of the AP spec file.

**Comment by jordonezlucena** [comment]
Telefonica agrees on updating API documentation template as noted above.
Telefonica also volunteers to provide the improved versions as showcases for [HomeDevicesQoD Sub-Project](https://github.com/camaraproject/HomeDevicesQoD)

**Comment by jordonezlucena** [comment]
> Telefonica agrees on updating API documentation template as noted above.
> Telefonica also volunteers to provide the improved versions as showcases for [HomeDevicesQoD Sub-Project](https://github.com/camaraproject/HomeDevicesQoD)

Here's the example: https://github.com/camaraproject/HomeDevicesQoD/blob/main/code/API_definitions/home_devices_qod.yaml. As you may notice, it is self-contained, as demanded in this issue. We propose this YAML can be used as example, mirrored accordingly for the rest of APIs.

**Comment by bigludo7** [comment]
One question: is it possible to embed in the OAS `description: ` part .jpg or .png ? For some API we need to provide sequence diagram to explicit resource use (like number verification) or to provide state engine (like for carrier billing).
If it is possible I'm fine with your proposal - if not that could be a problem for me to not have anymore the md doc.

**Comment by eric-murray** [comment]
@bigludo7 
Images can be inline linked using HTML. If the images are stored in the github, then using an absolute rather than relative URL should allow the image still to be rendered given only the OAS file itself, so long as the viewer also has an internet connection.
https://spec.commonmark.org/0.27/#images

**Comment by PedroDiez** [comment]
@shilpa-padgaonkar , @jordonezlucena What do you think about this topic?

Honestly speaking, think we are in the conditions to apply this guidance in every WG

**Comment by jordonezlucena** [comment]
Yes, ok for me. The API owner of each Sub-project shall open a PR to apply this.

**Comment by shilpa-padgaonkar** [comment]
/LGTM, Agree with Jose about subprojects creating relevant issue and PR.

**Comment by shilpa-padgaonkar** [comment]
With the proposal being accepted and relevant PRs in subproject being created, can we close this issue in commonalities?

**Comment by jordonezlucena** [comment]
Agree with Shilpa's proposal.

**Comment by shilpa-padgaonkar** [comment]
Based on the discussion in commonalities call on 01.06, this issue can now be closed.
