### ISSUE TITLE
version number on API Design Guidelines Doc [Commanalities]

### ISSUE THREAD

**Issue by murthygorty** [camaraproject/WorkingGroups#170]
Hi, 
I think it will be useful to put a version number on the Design Guidelines doc, just like the APIs themselves.
This will allow us to iteratively improve on the Design Guidelines and the implementation itself may lag behind a little.

Thoughts?

**Comment by jordonezlucena** [comment]
Hi,

TEF standpoint is that it makes sense to implement versioning for guidelines. 
However, what is important is to distinguish when a RFC means **evolution**, **new considerations** or **breaking changes**. For example, the outcome [issue#157](https://github.com/camaraproject/WorkingGroups/issues/157) resulted into a breaking change. With this distinction, if an approved RFC is breaking change, CAMARA APIs should be updated according this change, with this API update representing a major version. 
According to this rationale, we propose to mark current guidelines with v1.0.0 and move forward as proposed above.

**Comment by murthygorty** [comment]
I agree - this is a sound idea.

**Comment by eric-murray** [comment]
@murthygorty 
I agree adding an explicit version number to the design guidelines is a good idea, particularly when needing to refer to older versions of the guidelines. And I agree with the proposal from @jordonezlucena.

Can you confirm the intention is that the current "release" of the design guidelines will continue to be found in the main branch of the WorkingGroups repository, so there will be no "work in progress but unreleased" versions to be found there (unlike our OAS specifications)?

**Comment by murthygorty** [comment]
I didn't think of it when I raised the issue, but what you say makes sense @eric-murray. only 'released' design guidelines are in the main branch.
I'm wondering if it also makes sense to tag API spec with the version of the guideline it is following. cc: @shilpa-padgaonkar @gmuratk

**Comment by jordonezlucena** [comment]
@rartych @bigludo7. 
As for the versioning, we prefer to keep it with "API-design-guidelines-vx.y.z" format instead of "API-design-guidelines-vDD_MM_YYYY".
As for the change tracking, we agree on going for a separate changelong file.

**Comment by shilpa-padgaonkar** [comment]
The commonalities WG was created with an initial scope to create some best practice documents & discuss common issues that impact more than one Camara subproject. This scope over time has grown, and we have now reached a stage where we are creating artifacts such as [CAMARA_common.json](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/CAMARA_common.json) and others which will be referenced/reused by other subprojects.

One proposal would be to turn commonalities WG into a subproject of its own, where it will deliver these common artifacts (including documents) and have regular releases like other subprojects. This will allow other subprojects to refer to commonalities deliverables in a cleaner way.

Feedback/Alternatives for this proposal is appreciated.

**Comment by murthygorty** [comment]
Hi @shilpa-padgaonkar , that is an interesting notion. I don’t have a particularly strong preference 
- one aspect to carefully consider is that commonalities is in fact different from other API family or service API — typical service API fits a mold like spec, documentation, etc, but commonalities may have more than one spec and different documentations, what do you think?
- one of your notions that we should definitely pursue is your commoner about converting commonalities into a for that has releases etc. this would bode well when we get to common version for all Camara (like the grand Camara 1.0 for example).

cc:@gmuratk

**Comment by shilpa-padgaonkar** [comment]
@murthygorty : Thank you for your feedback. Yes I agree that the commonalities subproject will not be able to follow the usual template of other subprojects but I don't see this as a showstopper.

**Comment by murthygorty** [comment]
sounds good @shilpa-padgaonkar. I too believe that this can be done, the artifacts from this subprojects vary, but incorporating as a subproject will make the upcoming 'release' also uniform.

**Comment by shilpa-padgaonkar** [comment]
https://github.com/camaraproject/WorkingGroups/discussions/260

**Comment by shilpa-padgaonkar** [comment]
New repo created here https://github.com/camaraproject/Commonalities
Closing this issue.
