### ISSUE TITLE
commonalities: does camara_common belong in supporting documentation?

### ISSUE THREAD

**Issue by murthygorty** [camaraproject/WorkingGroups#172]
Looking at[ camara_common](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/CAMARA_common.json), I understand this to be a sample from Telefonica. Should this move into 'Supporting Documentation' folder?

**Comment by RubenBG7** [comment]
Hi @murthygorty , this is not a sample from TEF, this is part of the CAMARA API guidelines, supporting common data types title.

**Comment by shilpa-padgaonkar** [comment]
As agreed in wg call today, @RubenBG7  will update the doc (by creating a PR against this issue) so that it only includes Camara relevant entries.

**Comment by murthygorty** [comment]
Thanks both! I should have said as "content of camara_common" rather than "camara_common" itself :-)

**Comment by shilpa-padgaonkar** [comment]
@murthygorty : please review PR https://github.com/camaraproject/WorkingGroups/pull/176 to see if your concerns are addressed.

**Comment by jordonezlucena** [comment]
PR #176 completed and no further comments received over the last two weeks. I'll propose then to close this issue

**Comment by murthygorty** [comment]
thanks for closing @jordonezlucena @shilpa-padgaonkar - I'm good with the changes. Sorry for the delay, notifications were going to non-work email that I wasn't watching closely - I fixed it now.
