### ISSUE TITLE
suggestion: commanalities/design guidelines/error responses

### ISSUE THREAD

**Issue by murthygorty** [camaraproject/WorkingGroups#177]
I recently came across this very nice suggestion for error response. I suggest that
1) we use this as a guideline
2) we *not* prescribe the exact wording of the error message - it is likely operator specific.

![betterErrorMessage](https://user-images.githubusercontent.com/19613159/228055289-1a83e4fa-7258-4205-b707-d4b9604a98b6.png)

**Comment by RubenBG7** [comment]
Hi @murthygorty ,

This kind of errors typically returned by channels which ones interact with APIs and each channel make the interpretation of standard errors defined in guidelines. Message could be fulfilled on API level, but final channel could give its own error messages.
