### ISSUE TITLE
Version of OpenAPI specification to be used by subprojects

### ISSUE THREAD

**Issue by rartych** [camaraproject/WorkingGroups#184]
API Design Guidelines state in [ch.11](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/API-design-guidelines.md#11-definition-in-openapi): _The API functionalities must be implemented following the specifications of the Open API latest version_ .

The latest version of OAS is [3.1.0](https://spec.openapis.org/oas/latest.html) published on 15 February 2021. However, currently all subprojects use **3.0.3** version of OAS. 

Although it is not so complicated to [migrate from 3.0 to 3.1](https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0) it may be reasonable to stay with 3.0.3. The most of tools (even Swagger) do not fully support the latest OAS version.

Then the clarification in **API design guidelines** is needed.

**Comment by PedroDiez** [comment]
We agree to design based on **OAS v3.0.3**, as it is the consolidated version supported by majority of tools. 
Version v3.1.0 has limited support yet.

**Comment by RubenBG7** [comment]
Totally agree with @rartych and @PedroDiez
