### ISSUE TITLE
Release branches should be protected within all sub projects

### ISSUE THREAD

**Issue by hdamker** [camaraproject/WorkingGroups#186]
**Problem description**

The main branch is protected in all sub projects. But the release branches `release-x.x.x` which should according to [Camara_Versioning_Guidelines.md](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/SupportingDocuments/Camara_Versioning_Guidelines.md) be created are not protected and can be unintentionally changed.

**Expected behavior**

All branches within a sub project starting with the pattern`release-` should have the same protection as the `main` branch:
* Pull requests need be reviewed by at least one code owner before they can be merged

![image](https://user-images.githubusercontent.com/52109189/231537306-9362da6c-8c5c-482c-a0a0-918104259d44.png)

**Alternative solution**

**Additional context**

a) to be documented in [Camara_Versioning_Guidelines.md](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/SupportingDocuments/Camara_Versioning_Guidelines.md)
b) established by CAMARA admins within all sub projects

**Comment by jordonezlucena** [comment]
@hdamker: TEF is ok with this proposal. With the additional context... you mean the action points (which translate into corresponding PRs?)

**Comment by hdamker** [comment]
> a) to be documented in [Camara_Versioning_Guidelines.md](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/SupportingDocuments/Camara_Versioning_Guidelines.md)

Will be done with #195 

> b) established by CAMARA admins within all sub projects

Done: Branch rule for `release*` added in all Sub Projects and the Templates.
