### ISSUE TITLE
Proposal for a New API for E.212/E.164 Mapping

### ISSUE THREAD

**Issue by MarkusKuemmerle** [camaraproject/WorkingGroups#192]
I move this issue from @ajamous and @patrice-conil
from Governance repo to API Backlog Working Group:

Hello Team,

I’m writing to propose a new API for E.212/E.164 mapping (MCCMNC <->Dial Code) to create accurate and up-to-date mapping list available to the public. I believe that adopting this API under the CAMARA project has the potential to provide a single point of truth for E.212/E.164 mapping which doesn’t seem to exist anywhere at this time. This would enable anyone to find the most recent and accurate dial codes belonging to MCCMNC and vice versa globally, providing valuable information to users worldwide.

Our team has spent considerable time and resources to create this API, and we believe it could benefit the wider community greatly. We would be honored to contribute this new API/Data to the CAMARA project and work with your team to make it available to developers worldwide.

Please let me know if you are interested in learning more about this topic and how we can work together to make it available to wider community. I am happy to provide more details or answer any questions you may have.

Thank you for your time and consideration. I look forward to hearing back from you soon.

**Comment by jordonezlucena** [comment]
If you'd like to formally bring this API proposal to the backlog, please follow the steps described [here](https://github.com/camaraproject/Governance/blob/9d5cd1d216ef1e69c9eee297f69641309f03543e/documentation/API-onboarding.md). The first step is to fill in this [template](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/API-proposal-template.md)

**Comment by jordonezlucena** [comment]
> Thx @jordonezlucena will do.
Would be great if you could join next call (11th May) and clarify questions/comments from WG participants.

**Comment by patrice-conil** [comment]
Sync with @bigludo7,
I totaly agree with @eric-murray this API should only be exposed once.

**Comment by ajamous** [comment]
@jordonezlucena I have completed the first step of filling out the form (as shown below). Please review the information and let me know if you have any concerns or questions.

>>Would be great if you could join next call (11th May) and clarify questions/comments from WG participants.

Sounds good. I will do my best to be there and answer any questions/comments. 


Field | Description
-- | --
API family name | Dial Code Lookup API (E.212 to E.164 Mapping)
API family owner | TelecomsXchange
API summary | The Dial Code Lookup API provides up-to-date information on the mapping of dial codes (also known as calling codes or country codes) to countries and regions. Currently, there is no standardized mapping list for dial codes, and each operator creates their own list, which is often out-of-date. This API aims to standardize the mapping list to increase the accuracy of billing and routing and reduce disputes related to mis-matched dial code mapping. By accessing the Camara API, telecom solution software developers, such as IMS, Softswitches, and SMSCs, can easily and automatically pull updated dial codes as they change, improving the accuracy and reliability of their systems.
Technical viability | This API requires access to a database that contains the latest information on E.212 to E.164 mappings, I suggest https://github.com/ajamous/OpenMSISDNMapper as a start. The database should be updated on a regular basis to ensure the accuracy of the mappings. The API can be implemented using standard RESTful protocols, and it requires support for JSON and XML data formats.
Commercial viability | When TelecomsXchange built the SMS Exchange marketplace platform, we encountered difficulty accessing E.212 to E.164 mapping data as every operator maintains its own version of the list that is neither open-source nor available to the public. However, TelecomsXChange (TCXC) and its Partner, Telin (a subsidiary of Telkom Indonesia), have manually collected and built an extensive and up-to-date database using over 7 sources such as Wikipedia, GSMA, Tekom Group, and others. This database can be used to implement the API and is based on open-source software that is publicly available for download. To ensure that the API remains current and accurate, it would be advantageous to include an automated mechanism in the Camara API that allows operators to suggest dial code additions, removals, or changes through a pull request. This would enable operators to provide updates efficiently and effectively, ultimately keeping the API up-to-date with the latest mapping information.
YAML code available? YES | YAML sample is available on https://github.com/ajamous/OpenMSISDNMapper .
Validated in lab/productive environments? | YES, this list is being used by TCXC and Telin for the past 3 years to bill voice, SMS traffic for over 2 Billion transactions annually.
Validated with real customers? | YES.
Validated with operators? | YES.
Supporters in API Backlog Working Group | N/A

**Comment by jordonezlucena** [comment]
Hi @ajamous: submission instructions note that the filled-in template shall be submitted as a PR. Could you please take care of it?

**Comment by ajamous** [comment]
> Hi @ajamous: submission instructions note that the filled-in template shall be submitted as a PR. Could you please take care of it?

Sure, here you go: https://github.com/camaraproject/WorkingGroups/pull/206

**Comment by jordonezlucena** [comment]
#206 was closed. @ajamous: Do you want then stop pursuing this issue?
