### ISSUE TITLE
Security section in guidelines document contradicts the authN-authZ concept doc

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/WorkingGroups#197]
It is important that  we do not contradict one document in commonalities with another. The security section https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/API-design-guidelines.md#10-security in the guidelines document mentions "While basic authentication is good enough for most APIs and, if implemented correctly, also secure, you may want to consider OAuth as well." This seems to a reader that we can use basic auth but we could also use oauth2. (I unfortunately missed this in my initial review)

We have already agreed in https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/CAMARA-AuthN-AuthZ-Concept.md that we will use oauth2-oidc. Please simply remove this section from the doc and point to the already approved authN-aithZ doc under the security section for details or kindly keep the details compliant to the authN-authZ doc.

**Comment by RubenBG7** [comment]
Agree with your point @shilpa-padgaonkar , let me update changes.

**Comment by RubenBG7** [comment]
Fixed on #216
