### ISSUE TITLE
Camaraproject.org Scope section, aggregator should be optional?

### ISSUE THREAD

**Issue by murthygorty** [camaraproject/WorkingGroups#207]
Thanks @MarkusKuemmerle for guiding that I can raise issues against camaraproject.org over here in 'Marketing' WG.

Regarding the issue itself, looking at [camaraproject.org->Scope](https://camaraproject.org/scope/), I recommend that we update the diagram with these changes:
1) aggregator as optional. Consistent with the 'distribution options', API Consumer uses aggregator for some use cases, not necessarily all.
2) Include a Developer Platform as the interface to Developer - I realize that this may be an overarching topic since we could be expanding the scope beyond serviceAPI, but for now, it is realistic to expect that Developers (Consumers) use an interface and it may be useful to depict that.
3) reword Consumer to Developer or 'API Consumer' as in the operator world, it might mean the end customer. I realize this scope is API, so may be it is implied? perhaps that can be clarified somewhere then, in 'nomenclature' or 'glossary'

cc: @gmuratk

**Comment by MarkusKuemmerle** [comment]
We update the descriptions and all diagrams following the agreements between CAMARA, GSMA and TM Forum

**Comment by murthygorty** [comment]
Hi @MarkusKuemmerle , thanks for the info - is this issue fine where it is or do you need me to move it somewhere else, given your comments?

**Comment by MarkusKuemmerle** [comment]
Hi @murthygorty : Would you please check that I've included all of your feedback in the new scope description, and then close this issue?
