### ISSUE TITLE
OASG Summit

### ISSUE THREAD

**Issue by ShutingQing** [camaraproject/WorkingGroups#211]
Hi everyone, 

The OASG Summit is on going, which is **the most influential, and most high-level open-source summit** in China.

Here is a brief introduction. 

**Feature:** 
The most influential, and most high-level open source summit in China.
Date: 
2023.06.11 - 2023.06.13
**Theme:** 
Open Source Tech, Benefit All
**Event:** 
Onsite and Virtual
**Hosted by:** 
2023 Global Digital Economy Conference Committee
**Organized by:** 
Open Atom Foundation, Beijing Bureau of Economy and Information Technology, Beijing Economic-Technological Development Area Steering Committee
**Planning to Invite:** 
Ministry of Industry and Information Technology, Beijing Government, The Academicians of the Chinese Academy of Sciences and the Chinese Academy of Engineering, Top Global Open Source Foundations, Open-Source Domestic and International Influential Experts, Business Executives, and global media teams.

We see it as a great opportunity to promote CAMARA and network capability exposure globally here. Hopefully, more companies, espcially the end user companies in the industry, can know that we are doing this and why we're doing this. 

If community perceive it's good chance to promote CAMARA here, let's do this!

**Comment by ShutingQing** [comment]
Linked to [https://github.com/camaraproject/WorkingGroups/pull/210](url)

**Comment by MarkusKuemmerle** [comment]
Very success ful event!
