### ISSUE TITLE
New API proposal: Click to Dial

### ISSUE THREAD

**Issue by HanbaiWang** [camaraproject/WorkingGroups#217]
Hello Team,

I’m writing to ask for advise to propose a new API called Click to Dial. This API can helps companies calling this API to establish voice calls for their users, it also protects the privacy of the users of the company during the voice call. This API can be widely used in logistics and express industry, enterprise OA and other scenarios.

We find out that this API does not conflict with the 12 existing API sub projects in CAMARA. May I ask whether we can try to establish a new project for this API and make contributions to CAMARA through this API project? If possible, what is the relevant process? My understanding is that we first need to fill out the API proposal template, and then do some brief presentations at the weekly meeting of the API Backlog working group to introduce our new API. 

Any suggestions from you will be of great help to us. And if you have any question with this API, please feel free to ask me at anytime, Thank you!

**Comment by HanbaiWang** [comment]
Dear API Backlog Working Group members, In response to the last discussion, we've combed through some further information/details on Click-to-Dial API, including references to existing standard documents.This is presented in the following chunks.

**Comment by HanbaiWang** [comment]
![ed3454239a4b601fce1883bc35429b5](https://github.com/camaraproject/WorkingGroups/assets/131632520/bab9a3c5-f4c4-4609-995e-24a0a6d0ee91)
![1f9092f8297a9b39013ac1b9c627ee9](https://github.com/camaraproject/WorkingGroups/assets/131632520/ac96d47f-8020-4ce0-89e7-0d59af4e5092)
![4486ae5439522d75cea0c94de7305a9](https://github.com/camaraproject/WorkingGroups/assets/131632520/f3bab15b-6d17-4a5f-9157-bbe2e9530dcb)
![e7f17e7871c63ee3a146cdd1438414f](https://github.com/camaraproject/WorkingGroups/assets/131632520/1e47133b-717e-45f9-98ed-5c3921113635)
![2cb54bb5155225655fd3859307476e9](https://github.com/camaraproject/WorkingGroups/assets/131632520/ec66c694-395b-4a13-bbe0-7c0342c09939)
![0fb7ae3df304d056e37656c01a8d78f](https://github.com/camaraproject/WorkingGroups/assets/131632520/58040bce-87c3-4738-82ac-51f34e73ddc5)

**Comment by eric-murray** [comment]
Thanks @HanbaiWang
Are you still including support for 2G/3G circuit-switched voice calls in your requirements for this API and, if so, do you have similar slides for the technical solution for that case? Or is the assumption now that the CSP has a converged voice core where IMS manages all voice calls?

**Comment by HanbaiWang** [comment]
@eric-murray 
For China Mobile's click-to-dial APIs that are currently commercially available, China Mobile's click-to-dial service is supported to serve IMS and CS users. However, it cannot be ruled out that other operators may only support services to IMS users.

This click-to-dial project specifies the API functions and service forms, but does not strictly limit the scope of service users. This is because the scope of API services, especially whether it is necessary to support CS users or only IMS users, actually depends on the actual operator's operation strategy and the operator's network deployment. Therefore, it is not appropriate to strictly limit the service scope in this project. It is suggested that the service scope can be categorised according to the operator's service situation, such as: IMS users can be supported, IMS and CS users can be supported, and so on.

**Comment by HanbaiWang** [comment]
When the operator's network is adequately built (when the IMS and CS networks have been established and interoperability is complete). Click to Dial AS is supported to cover IMS with CS user services.

- The initiation of click-to-dial is actually the process of the AS to establish a call. According to the 3GPP standard, the caller is supported to establish a call to the CS domain user.
- As long as the operator's IMS network supports interworking with the CS network, the CTD AS can establish a call to the CS network user, that is, the CTD AS can complete the service to the CS user.
- If the IMS network need to support interworking with the CS network, the IMS network needs to contain a BGCF and an MGCF (refer to TS 23.228 5.2.7, TS 24.228 7.2.4 and related specification sections), where:

1. The BGCF is used for call routing from IMS to CS, the BGCF receives a call request from the S-CSCF and selects the appropriate MGCF for forwarding according to the local configuration.
2. The MGCF is used for interworking between the IMS domain and the CS domain, and is responsible for completing the interworking of control plane signalling (interaction and interworking of ISUP/BICC protocols on the PSTN/CS domain side and SIP protocols on the CM-IMS side)

**Comment by HanbaiWang** [comment]
When the CTD AS initiates a call to a CS domain user, the main idea of the technical solution is that the CTD AS initiates a call to the MGCF (which performs CS domain routing, and the choice of which MGCF depends on the construction and planning of the operator's network). Then MGCF device calls the CS domain signalling to the specified GMSC for CS domain pick-up calls based on number analysis. 
There are various options for the selection of MGCF, for example, a centralised MGCF can be specified for CS domain routing, or CS domain routing can be based on the MGCF to which the CTD AS caller number is attributed.

**Comment by HanbaiWang** [comment]
@jordonezlucena 
Hi Chair,
We previously submitted a request for a Click to Dial API project in the API Backlog working group, and we are very pleased to take our API for approval, could you please sends our Click to Dial API for approval on  7th Sept TSC meeting? Thank you！

**Comment by jordonezlucena** [comment]
The API owner (China Mobile) has asked to take the API proposal for approval to TSC meeting on 7th Sept.

**Comment by jordonezlucena** [comment]
The API proposal has been approved in the TSC meeting held in 7th Sept. 
As for next steps: 
- Supporting companies (China Mobile, Huawei) to propose their initial maintainers for the subproject (AP 20230907-06).
- TSC will collect this information, and decide to propose optional additional initial maintainers. The TSC will officially nominate the (list of) initial maintainers by next TSC meeting.
- CAMARA admins will create the subproject repository.

@HanbaiWang, @ShutingQing: propose your maintainers.

**Comment by ShutingQing** [comment]
Thanks Jose. For Huawei it's me will be maintaining this project. Shuting Qing/Miranda Tsing.

**Comment by HanbaiWang** [comment]
Thanks Chair. 
The maintainer of China Mobile will be Hanbai Wang.

**Comment by jordonezlucena** [comment]
Thanks @ShutingQing  and @HanbaiWang . I will inform TSC accordingly.
With the maintainers list completed, this issue is eligible to be closed next meeting.

**Comment by jordonezlucena** [comment]
A late comment. China Telecom just became supporter of this API proposal.
The maintainer will be Dan Xu (@DanXu-ChinaTelecom)

**Comment by jordonezlucena** [comment]
With the maintainers list completed, this issue is eligible to be closed next meeting.

**Comment by jordonezlucena** [comment]
[ClickToDial WG](https://github.com/camaraproject/ClickToDial) is created, so the issue can be closed
