### ISSUE TITLE
Updated api version notification for all/any api

### ISSUE THREAD

**Issue by sahidkhangithub** [camaraproject/WorkingGroups#219]
Hi Team, 

1. We are implementing CAMARA apis, if there is any update on any api signature or agreement, then how we(company who implemented/provided api) will be notified. So if need we can absorbe the change.
2. As we are tring to implement multiple CAMARA api, how we can certify these apis.

**Comment by shilpa-padgaonkar** [comment]
@sahidkhangithub 
For point1, you could simply use GitHub notifications to ensure that you are updated on the activities within a subproject.  You can also select custom notifications when you would like to subscribe to only specific activities of a subproject, for e.g. release notifications. 

For point2, could you kindly elaborate, what you mean by getting APIs certified?
