### ISSUE TITLE
New API proposal: Identity API

### ISSUE THREAD

**Issue by jordonezlucena** [camaraproject/WorkingGroups#239]
PR #237

**Comment by hdamker** [comment]
I propose to close the issue and PR and continue the work on the proposed API in existing sub project "Identity & Consent", starting with an user story for the API. See also comments on the PR.

**Comment by shilpa-padgaonkar** [comment]
I agree on closing this issue here and starting this discussion under identity and consent subproject

**Comment by MarkCornall** [comment]
Already an issue in Identity and consent. Can continue there. https://github.com/camaraproject/IdentityAndConsentManagement/issues/15
