### ISSUE TITLE
API versioning

### ISSUE THREAD

**Issue by Bart-Ericsson** [camaraproject/WorkingGroups#25]
The versioning mechanism for APIs is not defined
- [Semantic Versioning 2.0.0](https://semver.org/) is proposed to be followed
- Before an API is officially approved by majority vote in the working group, the version should be < 1.0

API versions shall try to maintain backward compatibility.
- API server is assumed to have the capability to support multiple API versions. And provide the same endpoint to support backward compatible versions and separated endpoints for non-backward-compatible versions.

**Comment by fatihrd** [comment]
Suggest to include _changelog_ handling into this issue as well, considering the close relationship with versioning.
https://keepachangelog.com/en/1.0.0/ structure is proposed.

**Comment by Kevsy** [comment]
> API versions shall try to maintain backward compatibility.

Agreed - and according to RESTful principles, the response to a deprecated API URL should indicate links where the client can go next, with link relations to explain what they do

Resource representations can be versioned with MIME-types, which also allows of content negotiation. i.e. client can add an 'Accept' header for accpetable versions of a resource representation, and if the server cannot fulfil that it can repond with 406 Not Acceptable, and list the acceptable reource representation version it can serve.

**Comment by T-sm** [comment]
Thank you for this proposal. It would be good to reflect this principles in our core documentation.
I propose to include it in General Principles, currently under review in Issue #32 - please do not hesitate to write if you have other/different suggestions.

**Comment by T-sm** [comment]
Closing this issue and moving the discussion to issue #32  as agreed during May 4th Commonalities Workgroup meeting.
The proposal will be reflected in the Versioning chapter of General Principles document.
