### ISSUE TITLE
New API proposal: KYC Fill-in

### ISSUE THREAD

**Issue by ToshiWakayama-KDDI** [camaraproject/WorkingGroups#267]

**Comment by ToshiWakayama-KDDI** [comment]
Hi @jordonezlucena ,
I cannot add the API Backlog label.  Could you advise me how to do it?

Thanks,
Toshi

**Comment by ToshiWakayama-KDDI** [comment]
PR #268

**Comment by ToshiWakayama-KDDI** [comment]
@shilpa-padgaonkar , Thank you very much.

**Comment by jordonezlucena** [comment]
The API owner (KDDI) has asked to take the API proposal for approval to TSC meeting on 7th Sept.

**Comment by jordonezlucena** [comment]
[KnowYourCustomer](https://github.com/camaraproject/KnowYourCustomer) Sub-Project is created, so the issue can be closed
