### ISSUE TITLE
New API proposal: Device Swap

### ISSUE THREAD

**Issue by jordonezlucena** [camaraproject/WorkingGroups#284]
#276

**Comment by jordonezlucena** [comment]
API voting is not included on the agenda for TSC meeting on 20th Sept meeting.

**Comment by jordonezlucena** [comment]
The API owner (MTN) has asked to take the API proposal for approval to TSC meeting on 5th October.

**Comment by jordonezlucena** [comment]
As [reported](https://github.com/camaraproject/Governance/blob/main/documentation/MeetingMinutes/TSC/TSC-2023-10-05-Meeting-Minutes.md) in the TSC meeting held in 5th Oct, the API is pre-approved. Formal approval will come in Oct 19th, after TSC solving the family name to launch this API works.

As for next steps:
- Supporting companies (MTN, KDDI, Huawei) to propose their initial maintainers for the subproject.
      - @wwAMRA @ToshiWakayama-KDDI @ShutingQing: propose the maintainers from your companies

- TSC will collect this information, and decide to propose optional additional initial maintainers. The TSC will officially nominate the (list of) initial maintainers by next TSC meeting. 
- CAMARA admins will create the subproject repository.

**Comment by jordonezlucena** [comment]
> Hello @jordonezlucena One comment: My understanding of last TSC (https://github.com/camaraproject/Governance/blob/main/documentation/MeetingMinutes/TSC/TSC-2023-10-05-Meeting-Minutes.md) about this API is that we will (probably) not creating a new specific WG but add this API in an existing one. SIM Swap was the candidate but with a name change.
> 
> If we doing this way I'm not sure about the maintainers management by the way.

In the minutes, it is noted the action for APIBacklog WG to nominate the maintainers, so that that the repo can be setup immediately after the TSC decision about family name. My reading for these notes is that a new Sub-Project is to be defined, hence the need for API supporters to nominate maintainers.

**Comment by ShutingQing** [comment]
> As [reported](https://github.com/camaraproject/Governance/blob/main/documentation/MeetingMinutes/TSC/TSC-2023-10-05-Meeting-Minutes.md) in the TSC meeting held in 5th Oct, the API is pre-approved. Formal approval will come in Oct 19th, after TSC solving the family name to launch this API works.
> 
> As for next steps:
> 
> * Supporting companies (MTN, KDDI, Huawei) to propose their initial maintainers for the subproject.
>   - @wwAMRA @ToshiWakayama-KDDI @ShutingQing: propose the maintainers from your companies
> * TSC will collect this information, and decide to propose optional additional initial maintainers. The TSC will officially nominate the (list of) initial maintainers by next TSC meeting.
> * CAMARA admins will create the subproject repository.

@jordonezlucena Thanks Jose, The api contributor will be Shuting Qing.

**Comment by jordonezlucena** [comment]
Repository, mailing list and website update are done for [DeviceSwap](https://github.com/camaraproject/DeviceSwap). Work will continue in the sub-project from now on.
