### ISSUE TITLE
New API Proposal- Network Insights

### ISSUE THREAD

**Issue by maheshc01** [camaraproject/WorkingGroups#294]
The API enables App Developers to define intents in the form of policy thresholds for QoS metrics against the device and the application service. The API service will alert the consumers if and when the policy has breached. This API would be useful for applications that optimize user experience based on the user's network experience.

**Comment by maheshc01** [comment]
i would like to label this issue as API Backlog but looks like i dont have the permissions as i dont see any option to label it.
@Kevsy could you help me with adding the label or let me know how i could do it?

**Comment by ShutingQing** [comment]
Hi Maheshc, may we have more details for network insight? @maheshc01

**Comment by jordonezlucena** [comment]
> Hi Maheshc, may we have more details for network insight? @maheshc01

This is also captured as action point in the [minutes of last conf. call](https://github.com/camaraproject/WorkingGroups/pull/303/files), particularly in AP 20230907-04. @maheshc01: could you please take action accordingly?

| AP Identifier | AP Owner | Status | Description |
| ------------- | -------- | ------ | ----------- |
| 20230907-04 | Verizon | Open | To fill missing information on technical viability for [Network Insights API proposal](https://github.com/camaraproject/WorkingGroups/pull/295). |

**Comment by maheshc01** [comment]
> Hi Maheshc, may we have more details for network insight? @maheshc01

have updated technical viability as well as included the yaml file in the pull request.

**Comment by maheshc01** [comment]
> > Hi Maheshc, may we have more details for network insight? @maheshc01
> 
> This is also captured as action point in the [minutes of last conf. call](https://github.com/camaraproject/WorkingGroups/pull/303/files), particularly in AP 20230907-04. @maheshc01: could you please take action accordingly?
> 
> AP Identifier	AP Owner	Status	Description
> 20230907-04	Verizon	Open	To fill missing information on technical viability for [Network Insights API proposal](https://github.com/camaraproject/WorkingGroups/pull/295).

the updates have be submitted as per the discussion we had along with the yaml.
Please let me know if any additional information is required.

**Comment by ShutingQing** [comment]
Hi Mahesh, could you pls elaborate more about the policy and the intent here? For the policy here, does it stands for line 232-275? Can i understand the policy here is more likely for the usage of network configurations? I'm wondering if there any other considerations for the naming it policy.  For the implementation here, may i know is there any standard network sight is following? @maheshc01 Thanks at first.

**Comment by jordonezlucena** [comment]
@maheshc01: thanks for filling out the technical availability clause. In this new clause, it is noted that this API can rely in QoS monitoring mechanisms reported in TS 23.501 v18.2.2, section 5.45. A number of questions in this regard:

- The document you point is Rel-18 version (v18.x.y), which means 5G-Advanced. Could we point to a Rel-15 version (to make sure most operators can have it deployed as of today)? 
- Section 5.45 points to this QoS metrics: i) UL packet delay, DL packet delay, round trip packet delay; ii) Congestion; iii) Data Rate; iv) packet delay variation; v) Round trip packet delay when UL and DL are on different QoS flows. Which of them would be in scope of this API proposal, according to Verizon/5GFF experience? To manage expectations from developers (API consumers) and implementors (which will need to decide which is the functional scope of each API release).
- It is claimed that this API also work for 4G (before Rel-15). Could you provide a pointer to the 3GPP spec accordingly (23.501 is only for 5G)?

**Comment by jordonezlucena** [comment]
API voting not included on the agenda for TSC meeting on 20th Sept meeting.

**Comment by maheshc01** [comment]
it was a good discussion during the API backlog call. thank you for all the feedback.
Summarizing the key points:
1) the types of data required and possible sources. 
2) Implementation to support the API will be proprietary depending the input data sources available within each network operator but the Northbound interface is what is the focus here to be standardize for the developer community.
3) the proposed yaml has 5 KPIs among which 4 of them are also present in QoD latest API spec and the 1 not present is Latency. My proposal is to keep the API yaml as is to take it into a CAMARA working group (post TSC approval) and let the active members decide on the final list of KPIs with the guiding rule of limiting it to what is available in QoD.
4) This API will evolve along with QoD and Network Slice API in future with the objective of addressing the developer intent of network performance visibility.

**Comment by maheshc01** [comment]
> Hi Mahesh, could you pls elaborate more about the policy and the intent here? For the policy here, does it stands for line 232-275? Can i understand the policy here is more likely for the usage of network configurations? I'm wondering if there any other considerations for the naming it policy. For the implementation here, may i know is there any standard network sight is following? @maheshc01 Thanks at first.

Hi,
The intent we are trying to address here is to provide network performance insights to the application developers based on specific requirements of the application. And the term Policy is used with reference to network performance monitoring policy as defined by the developer who also wish to be notified for if any violations occur so that appropriate actions can be taken.

**Comment by maheshc01** [comment]
@jordonezlucena responded to all the comments. Please let me know if this API proposal is considered ready for next TSC meeting or any further clarifications are required.

**Comment by bigludo7** [comment]
@jordonezlucena Probably we can get challenged with TMF API offering same feature. I understood that TMF628 is leveraging in NICE Catalyst in a similar context.
@maheshc01 any thoughts on that ?
Adding @pjhac from AT&T in the loop.

**Comment by maheshc01** [comment]
hi @bigludo7 thank you for sharing about TMF628. I had not seen the spec before.
here is the link i used to learn more about TMF628: https://github.com/tmforum-apis/TMF628_Performance/blob/main/README.md

CAMARA APIs are more focused on Service APIs which are Application and Developer focussed, addressing specific intents. After going over the information related to TMF628 i definitely dont find it to be overlapping with what we are trying to address with Network Insights API. Probably they could play some role as an underlying API which the operators can choose to take advantage of but dont see it playing the role of north bound API for application developers.
This is my take based on the information i got to read. If i am missing out on any additional information or there are different perspectives to look at this, request others to share their thoughts.

**Comment by bigludo7** [comment]
Thanks @maheshc01 for your analysis.

Could you please take a look on the TMF catalyst itself ? https://www.tmforum.org/catalysts/projects/C23.0.513/nice-api-network-insights-for-customer-experience 

More than the 'pure' TMF628  API, this is the context of use in this catalyst that triggered my point.... but perhaps I miss the point. Appreciate your feedback. Thanks

**Comment by maheshc01** [comment]
@bigludo7 again, thanks for sharing additional details. it was very informative. 

Conceptually i see alignment on the problem statement we are trying to address.
NICE Catalyst looks like an extensive end to end solution and good reference architecture for operators looking to expose visibility of network performance.
Scope for CAMARA API is much more smaller and focussed on north bound interface to ensure easy to use for developers.
My request would be for NICE API team to review the proposed API spec here in CAMARA, share their inputs and also consider adopting it as north bound API spec in NICE APIs.

**Comment by jordonezlucena** [comment]
The API owner (Verizon) has asked to take the API proposal for approval to TSC meeting on 19th October

**Comment by FrimanJan** [comment]
The name "Network Insight" is a bit misleading. It would be better to name it something like "Connectivity Insight" as it is not the network as such that is focus but instead a specific connectivity.  "The API enables App Developers to define intents in the form of policy thresholds for QoS metrics against the device and the application service"  
Other suggestion could be Connectivity Monitoring, Device Connection Monitoring etc.

**Comment by sashankatakeon** [comment]
Hi All,
I am looking for something similar to this topic and hence the query on this thread.
Would it be possible to define following service from application to network:-
a) Ability of application to get defined KPIs from OSS
b) Ability of application to start/stop trace for specific UEs in particular Network node
c) In turn after stop of trace Network node uploads trace to application

This is of interest to do Network log analysis in kind of a seamless mode

**Comment by jordonezlucena** [comment]
I suggest having this discussion once the Sub-Project is up and running (API is approved and the sub-project will be opened shortly, pending closing some pending management-related issues)

**Comment by jordonezlucena** [comment]
The API was approved by TSC on 19th October. 
The API is allocated into a new Sub-Project, [ConnectivityInsights](https://github.com/camaraproject/ConnectivityInsights), which is now up and running.
The issue can be closed
