### ISSUE TITLE
E/// proposal for Authorization scope

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/WorkingGroups#3]

**Comment by T-sm** [comment]
The presentation mentioned above has been moved to WorkingGroups repo [here](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Contributions/Camara%20assumptions%20and%20missing%20concepts.pdf).

**Comment by jordonezlucena** [comment]
It is not clear to me what feedback is supposed to be provided in relation to point 2. Are we supposed to outline a solution to link API authorisation params with network authorization params (e.g. credentials stored in the UDM)?
I think it depends on the use scenario/use case under consideration. Let's take QoD API as an example, and assume that the UE wants to control QoS on a session established with a certain (group of) application(s), e.g. gaming applications. Thinking out loud, I foresee at least the following scenarios: 
- MNO is application provider -> the the application is provided by the MNO, i.e. no 3rd party involved. 
- MNO is reseller v1 -> the application is provided by 3rd party, but the UE has no contract signed to the 3rd party. 
- MNO is reseller v2 -> the application is provided by 3rd party, but the UE has no contract signed to the 3rd party.

**Comment by jordonezlucena** [comment]
No discussions/replies in this thread for long time. 
The focus of this issue is on this point: **Recipient of the service (for eg. UE) must be authorized to receive the service (for eg. QoD modification)**. As pointed out in the last comment, not sure which feedback the group expects to receive.

**Comment by shilpa-padgaonkar** [comment]
As stated above, presentation uploaded.
Issue labeled as stale. Closing issue.
