### ISSUE TITLE
API Proposal Template - new location

### ISSUE THREAD

**Issue by rartych** [camaraproject/WorkingGroups#309]
Since the Commonalities WG documentation is prepared to be archived - PR https://github.com/camaraproject/WorkingGroups/pull/265
I propose to move https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/API-proposal-template.md to new location in APIBacklog folder like:
https://github.com/camaraproject/WorkingGroups/tree/main/APIBacklog/documentation

I am aware of hyperlinks from https://github.com/camaraproject/Governance/blob/main/documentation/API-onboarding.md
Are there any other hyperlinks?

**Comment by hdamker** [comment]
@jordonezlucena would take care of it?

**Comment by jordonezlucena** [comment]
> @jordonezlucena would take care of it?
Yes, noted. I'll proceed with this next week.

**Comment by jordonezlucena** [comment]
@rartych  @hdamker : any preferred option between 1 and 2 above?

**Comment by rartych** [comment]
I am fine with option 1 - I've just indicated that changing location of the template implies update of [API-onboarding.md](https://github.com/camaraproject/Governance/blob/main/documentation/API-onboarding.md).

I hope we can improve access to the documentation with the help of Linux Foundation and new tools (like Wiki).
