### ISSUE TITLE
Dedicated Portal Instance for CAMARA

### ISSUE THREAD

**Issue by jordonezlucena** [camaraproject/WorkingGroups#31]
- The idea would be to have a single, unified portal instance for the entire project, hosting the different APIs developed and with tools allowing for their management (source code, documentation, etc.).

- TEF has a portal with API management capabilities that can be reused for CAMARA. The idea is to make people aware of these capabilities, and assess if CAMARA find them useful. If so, TEF could build out a dedicated portal instance for CAMARA project (tailored the initiative needs, including branding). 

- The action is on partners to check the PDF uploaded (https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Working/API%20Portal%20Capabilities.pdf), and take a 'go' / 'no-go' decision accordingly.

**Comment by jordonezlucena** [comment]
The presentation has been updated. Please, check

**Comment by T-sm** [comment]
Thank you very much for the proposal!
I find that such a portal may be crucial for further Camara's API development and support this idea.
The decision will be voted during the next Commonalities meeting.
If there is no quorum, the voting may be continued asynchronously within this issue.

P.S. In line with request #35  the presentation has been moved to https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Working/API%20Portal%20Capabilities.pdf

**Comment by Kevsy** [comment]
Per discussion at last meeting I've added [API development portal requirements] (https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Working/API%20development%20portal%20requirements). Once agreed we can make a decision on how to deliver them.

**Comment by jordonezlucena** [comment]
Hi @Kevsy: I'm not sure whether we're in position to deliver all these dev related capabilities with the solution we proposed. At least, the points captured below I'm not 100% sure we have them ready in the portal. 

- API testing automation against CAMARA commonalities/API principles
- Sandbox execution of API requests against local stubs (dummy data)
-- API consumer AuthN/AuthZ capability for executing the dummy API requests

Let me check with my colleague Rubén and come back to you.

**Comment by RubenBG7** [comment]
Hi @Kevsy. I'm trying to review the API development portal instance requirements that you published in 4 hour ago comment and i cannot get it. GIthub returns me a 404. Could you attach it again?

**Comment by Kevsy** [comment]
Sorry Ruben! I renamed the file as .md and forgot to update the link above. It is [here](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Working/API%20development%20portal%20requirements.md)

**Comment by Kevsy** [comment]
[API development portal requirements](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Working/API%20development%20portal%20requirements.md) updated with Postman Enterprise and Stoplight.io for comparison.

**Comment by MarkusKuemmerle** [comment]
I would keep it simple for the beginning an start with a simple table. Please sync with API Backlog group, it would be great to have only 1 table for backlog and APIs in development / production.

**Comment by MarkusKuemmerle** [comment]
See https://github.com/camaraproject/WorkingGroups/issues/53

**Comment by shilpa-padgaonkar** [comment]
We can accept this as a temporary solution for now.

**Comment by jordonezlucena** [comment]
@shilpa-padgaonkar: the issue was closed but the topic for discussion deviated into 'API backlog', which is far from what originally intended: "Dedicated Portal Instance for CAMARA". Would it make sense to re-open this issue again and provide an action plan towards SteerCo?

**Comment by shilpa-padgaonkar** [comment]
@jordonezlucena : Sure, you can reopen this issue with the scope to create an action plan towards Steerco. I will assign the issue to you.

**Comment by jordonezlucena** [comment]
Thanks. We are working out this internally. We'll prepare something for discussion (and potentially ballot) for upcoming SteerCo.

**Comment by jordonezlucena** [comment]
Dear all,

We have made a cost analysis on the platform, computing both CAPEX and OPEX. See costs deseeded below

| Item (Category) | Concept  | Cost  | Details |
-- | -- | -- | --
| C1 (CAPEX) | Portal instance creation | ~15 K€ | 1 month to get the portal up and running |
| C2 (OPEX) | Hosting (infra) | 500 € (peanuts) | Hosting in Azure 1
| C3 (OPEX) | Support and maintenance | ~20K€ | Estimated effort = 2,5 PMs/year. 8x5 support |


**Executive Summary**
| Year | Cost | Details |
| -- | -- | -- |
| Y1 | 35K€ | C1+C2+C3|
|Y2, Y3, …. | 20K€ | C2+C3|


As we are been informed that these costs will not be eligible for Linux Foundation (and we foresee it might be difficult for CAMARA partners to contribute to these costs), we have decided not to go ahead with the Portal offering. Therefore, it is proposed to close this issue.

**Comment by shilpa-padgaonkar** [comment]
Closing the issue as suggested by @jordonezlucena
