### ISSUE TITLE
Updates Required for Anonymised Subscriber Identifier Proposal

### ISSUE THREAD

**Issue by eric-murray** [camaraproject/WorkingGroups#312]
Hi All

If you look in the supporting documents folder, you will see a [proposal ](https://github.com/camaraproject/WorkingGroups/blob/main/APIBacklog/documentation/SupportingDocuments/API%20proposals/APIproposal_AnonymisedSubscriberIdentifier_Vodafone.md) for an Anonymised Subscriber Identifier API, but no mention of this in the [backlog table](https://github.com/camaraproject/WorkingGroups/blob/main/APIBacklog/documentation/APIBacklog.md).

In fact, this API was approved, but now lives in a private repository, which you will find [here ](https://github.com/camaraproject/AnonymisedSubscriberIdentifier) (if you have access). The reason it is private is because there was confusion around the intended use case (as described in the proposal) after the API was approved, specifically:
- hashing, even with the addition of both an operator and API consumer specific salts, does not make an identifier "anonymous"
- the proposal did not define how end user consent would captured and enforced, as CAMARA had not discussed the mechanisms for this at that time

The TSC has now decided that CAMARA should not support private repositories, so I'm opening this issue to discuss how the original [proposal](https://github.com/camaraproject/WorkingGroups/blob/main/APIBacklog/documentation/SupportingDocuments/API%20proposals/APIproposal_AnonymisedSubscriberIdentifier_Vodafone.md) (and possibly the [API definition](https://github.com/camaraproject/AnonymisedSubscriberIdentifier/blob/main/code/API_definitions/CAMARA%20Anonymised%20Subscriber%20Identifier%20API.yaml) itself) should be modified to avoid a recurrence of the use case confusion and allow the repository to once again be made public.

If you have a view on this, please comment in this issue so that a collective view can be formed. I'd like a final decision on this API to be taken at the next TSC meeting on 5th October, so comments by Monday 2nd October would be appreciated.

There is also the opportunity to apply the learning from this exercise to other API proposals.

@bigludo7 Maybe you could include a link to this issue in the TSC minutes

**Comment by FrimanJan** [comment]
Hi Eric. Can you grant me access ?

**Comment by eric-murray** [comment]
Closing issue
