### ISSUE TITLE
Does backlog table need updates for simswap?

### ISSUE THREAD

**Issue by murthygorty** [camaraproject/WorkingGroups#315]
our backlog table is showing two variants of sim-swap and the links there are not working - likely because it's merged into uber simswap family (which is real nice). can we update the table too please?
![image](https://github.com/camaraproject/WorkingGroups/assets/19613159/f42b8e82-5642-4985-ae99-f2ee219b565b)

**Comment by jordonezlucena** [comment]
yes, I need to do a clean-up for the entire table. I'm waiting for the outcomes of two pending issues before taking action. They may get solved by the end of next week

**Comment by murthygorty** [comment]
sounds good, thank you!

**Comment by jordonezlucena** [comment]
Activity already captured in [#100](https://github.com/camaraproject/Governance/issues/100).
