### ISSUE TITLE
Review General Principles doc 

### ISSUE THREAD

**Issue by jordonezlucena** [camaraproject/WorkingGroups#32]
ToC is available at https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Working/General-principles-doc.md

Document is available at https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Working/Guidelines%20API%20v1.0.0%20-%20CAMARA.pdf

**Comment by T-sm** [comment]
Thank you for your work on this documentation.
Please see also if issue #25 (API Versioning) proposals can be further incorporated into chapter 5 (Versioning). Thank you!

**Comment by jordonezlucena** [comment]
Hi, document was accidentally removed. Here's the new link, now placed under /working folder. https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Working/Guidelines%20API%20v1.0.0%20-%20CAMARA.pdf

**Comment by Kevsy** [comment]
Has the TOC moved as well? I get a 404. At least it's a Star Wars 404 on May the 4th ;)

**Comment by jordonezlucena** [comment]
> Has the TOC moved as well? I get a 404. At least it's a Star Wars 404 on May the 4th ;)

The links for both TOC and documents have been updated. Plz check now

**Comment by T-sm** [comment]
Added new subchapters proposals for Camara-specific aspects to be reflected in General principles as pull request (issue #41):
-API naming convention for Camara
-Versioning:
   &nbsp; &nbsp;*Agreement on major version 
   &nbsp; &nbsp;*Version change history
  &nbsp; &nbsp;*Repository tagging and releases
I already started working on expanding the Versioning chapter (in fact the included proposal reflects issue #25 points).
The issue #41 was opened along with the pull request (PR) and can be closed as soon as PR is accepted/rejected.

**Comment by Kevsy** [comment]
Suggestion added inline to #41

**Comment by jordonezlucena** [comment]
New version is made available by #72

**Comment by shilpa-padgaonkar** [comment]
@jordonezlucena : should this issue be marked as duplicate and closed?

**Comment by jordonezlucena** [comment]
This issue and #96 target the same topic. Closing this issue and continued in #96 .
