### ISSUE TITLE
New proposal for KYC Age verification

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/WorkingGroups#324]
https://github.com/camaraproject/WorkingGroups/pull/323

Note for @ToshiWakayama-KDDI : I assume this proposal should not be a new API project but part of KYC group under your lead.

**Comment by jordonezlucena** [comment]
The WG decided in last conf. call (see [minutes](https://github.com/camaraproject/WorkingGroups/blob/main/APIBacklog/documentation/MeetingMinutes/MOM-2023-11-02.md)) to take this API proposal for approval to TSC meeting on 16th October.
