### ISSUE TITLE
New Proposal- RegionUserCount

### ISSUE THREAD

**Issue by chinaunicomyangfan** [camaraproject/WorkingGroups#328]
PR-https://github.com/camaraproject/WorkingGroups/pull/327

**Comment by jordonezlucena** [comment]
Issue related to #334

**Comment by jordonezlucena** [comment]
The API proposal has been approved in the TSC meeting held in 7th Dec -- minutes available [here](https://wiki.camaraproject.org/display/CAM/2023-12-07+TSC+Minutes)

As for next steps:
- Supporting companies (China Unicom, Huawei) to propose their initial maintainers for the subproject. 
- TSC will collect this information, and decide to propose optional additional initial maintainers. The TSC will officially nominate the (list of) initial maintainers by next TSC meeting.
- CAMARA admins will create the subproject repository.

**Comment by jordonezlucena** [comment]
> The API proposal has been approved in the TSC meeting held in 7th Dec -- minutes available [here](https://wiki.camaraproject.org/display/CAM/2023-12-07+TSC+Minutes)
> 
> As for next steps:
> 
> 1. **[Supporting companies]** China Unicom and Huawei to propose their initial maintainers for the subproject @chinaunicomyangfan @ShutingQing
> 
> * The maintainers proposed need to be listed [here](https://github.com/camaraproject/Governance/blob/main/PARTICIPANTS.MD).

The proposed maintainers communicated by China Unicom and Huawei are @chinaunicomyangfan and @philipxujin.

**Comment by jordonezlucena** [comment]
@philipxujin should be added to [PARTICIPANTS.MD](https://github.com/camaraproject/Governance/blob/main/PARTICIPANTS.MD).

The information on proposed maintainers have been sent to TSC.

**Comment by philipxujin** [comment]
@jordonezlucena , already add my information into PARTICIPANTS.MD, now state is waiting for review

**Comment by jordonezlucena** [comment]
> @jordonezlucena , already add my information into PARTICIPANTS.MD, now state is waiting for review

Hi @philipxujin, I see you're done with your pending action as per [#114](https://github.com/camaraproject/Governance/pull/114). In an answer to the TSC list, @hdamker will officialise this along with the readiness to create the sub-project.

**Comment by jordonezlucena** [comment]
The API is allocated into a new Sub-Project, [RegionUserCount](https://github.com/camaraproject/RegionUserCount), which is now up and running.
The issue can be closed
