### ISSUE TITLE
TM Forum API mapping

### ISSUE THREAD

**Issue by MarkusKuemmerle** [camaraproject/WorkingGroups#33]
Please find an internal contribution from Orange on the Camara API Whishlist linked to TMF APIs; it has not been reviewed  with TMFs organization yet.
I think t would be a great opportunity to discuss it with our APIs TMForum expert Ludovic Robert.
Perhaps it could fine to discuss it in the appropriate stream inside Camara to further analyze APIs implementation and link to standards.

https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Contributions/Camara%20-%20Mapping%20API%20TM%20Forum%20-%20v0.docx

UPDATE: Presentation shown on May 18th during the Commonalities Workgroup meeting:
[May 18th Camara meeting v2.pptx](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Contributions/May%2018th%20Camara%20meeting%20v2.pptx)

**Comment by T-sm** [comment]
A big thank you to Orange's Ludovic Robert for the contribution! 
The [presentation](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Contributions/May%2018th%20Camara%20meeting%20v2.pptx) has been shown and discussed during the [Commonalities meeting](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/MeetingMinutes/MOM-2022-05-18.md) today.

**Comment by jordonezlucena** [comment]
Word document also elaborated and posted at [documents/contributions folder](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Contributions/Camara%20-%20Mapping%20API%20TM%20Forum%20-%20v0.docx).

**Comment by shilpa-padgaonkar** [comment]
stale issue. No further action needed.
