### ISSUE TITLE
New Proposal - OGW Dynamic People Density Information

### ISSUE THREAD

**Issue by jgarciahospital** [camaraproject/WorkingGroups#334]
Part of OGW drop3 - To align with proposal from China Unicom (To align with RegionUserCount API)

**Comment by jordonezlucena** [comment]
Issue related to #328 -- both need to discussed together

**Comment by jordonezlucena** [comment]
The API proposal has been approved in the TSC meeting held in 7th Dec, with some activities for the APIBacklog WG to act upon -- minutes available [here](https://wiki.camaraproject.org/display/CAM/2023-12-07+TSC+Minutes).

As for next steps:
1. **[API owner]** Decide naming for the Sub-Project hosting the API proposal @jgarciahospital 
- ConnectivityInsights is not the right sub-project. Neither is Device Location. TSC concludes that the API proposal needs to be allocated into a new sub-project.
- API (and this the sub-project)needs to be renamed, as current naming is confusing. TSC first suggestion is "Population Density Prediction".
2. **[API owner, API backlog]** Look for another company that wants to become supporter for this API @jgarciahospital 
- For a sub-project to be open, CAMARA requires having maintainers from at least two supporting companies. In the [backlog table](https://github.com/camaraproject/WorkingGroups/blob/main/APIBacklog/documentation/APIbacklog.md), only Telefónica appears. There is a need to have another company onboard.
- To move forward, a delegate from another company should submit a Pull Request against the [backlog table](https://github.com/camaraproject/WorkingGroups/blob/main/APIBacklog/documentation/APIbacklog.md), by adding the company name in the column "Supporters in API Backlog Working Group" for this API. 
3. **[Supporting companies]** Once action 2 above is completed, the supporting companies shall propose their initial maintainers for the subproject.
- These maintainers need to be listed [here](https://github.com/camaraproject/Governance/blob/main/PARTICIPANTS.MD). 
4. **[TSC]** to collect information from 1 dn 3, and decide to propose optional additional initial maintainers. The TSC will officially nominate the (list of) initial maintainers.
5. **[CAMARA admins]** Create the subproject repository, following official nomination from TSC.

**Comment by jgarciahospital** [comment]
1. Name proposal for API (and, therefore, subgroup) is "Population Density Data".
2. Vodafone has already openned a PR to be included as supporter/maintainer.

**Comment by jordonezlucena** [comment]
Thanks @jgarciahospital.

For step 3:
- @jgarciahospital: who will be the maintainer from Telefónica?
- @eric-murray @Kevsy : who will be maintainer from Vodafone?

**Comment by Kevsy** [comment]
@jordonezlucena me for Vodafone

**Comment by jgarciahospital** [comment]
me for Telefoncia

**Comment by jordonezlucena** [comment]
Thank you @Kevsy @jgarciahospital. This information is sent for TSC to process.

**Comment by Kevsy** [comment]
@jordonezlucena please may we change the Vodafone delegate to @sachinvodafone ?

**Comment by jordonezlucena** [comment]
> @jordonezlucena please may we change the Vodafone delegate to @sachinvodafone ?

yes, TSC is aware of this change and notified accordingly.

**Comment by jordonezlucena** [comment]
The TSC has approved the new API proposal with no further changes. 
API is allocated into a new Sub-Project, [PopulationDensityData](https://github.com/camaraproject/PopulationDensityData), which is now up and running.
The issue can be closed.
