### ISSUE TITLE
New Proposal for Device Location Retrieval

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/WorkingGroups#343]
https://github.com/camaraproject/WorkingGroups/pull/342

**Comment by jordonezlucena** [comment]
@bigludo7: Do you have a proposal on which sub-project should host this API proposal? Is it [DeviceLocation](https://github.com/camaraproject/DeviceLocation)? Or do you propose a new Sub-Project?
In case of a new Sub-Project, a new repo should be created, with maintainers/codeowners from a least TWO companies. As for now, this API proposal has only Orange as supporting company in the [backlog table](https://github.com/camaraproject/WorkingGroups/blob/main/APIBacklog/documentation/APIbacklog.md), so it'd be good to look for another supporting company.

**Comment by jordonezlucena** [comment]
The API proposal has been approved in the TSC meeting held in 18th Jan, with no further actions point for the APIBacklog WG -- minutes available [here](https://wiki.camaraproject.org/display/CAM/2024-01-18+TSC+Minutes).
The work can go on [DeviceLocation] (https://github.com/camaraproject/DeviceLocation) and the issue can be closed.
