### ISSUE TITLE
Markdown instead of PDF

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/WorkingGroups#36]
Please can we have a principle to use markdown instead of PDF for contributions? It will make Pull Requests much easier :)

**Comment by T-sm** [comment]
The authors of the core commonalities documents agreed to convert their contributions in other formats into markdown.
Therefore I am closing this proposal as unanimously accepted.

Please note that non-core documents (i.e. not Camara Commonalities deliverables, e.g. one-off contributions or slides that do not require a review and acceptance by the working group) can still be presented also in other formats.
