### ISSUE TITLE
API portal requirements doc update

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/WorkingGroups#37]
@Kevsy : As discussed in the commonalities call on 04.05 could you kindly add 2 new columns to the doc:-

1. To specify if the feature is mandatory or not
2. To specify which feature is already a part of a suggested solution(in our case the Telefonica portal)/solutions. Here @jordonezlucena can kindly add check marks where applicable.

**Comment by Kevsy** [comment]
Table now added with suggested values for mandatory/optional. Thanks @RubenBG7 for confirming the portal capabilities.

Please can the team check the Mandatory/Optional values I have suggested?

For reference I have added another column for comparison, '3rd party tool', in case we want to consider other candidates.  I will research if Postman Enterprise meets the requirements, but please fell free to add any other candidates in case we decide to choose between options.

**Comment by T-sm** [comment]
As discussed during last commonalities meeting:
since part of this discussion as well as the link to the requirements file is being held within issue #31, I am closing this issue and we will continue in #31 for clarity.
