### ISSUE TITLE
Cámara

### ISSUE THREAD

**Issue by Felipeparra24** [camaraproject/WorkingGroups#423]
Ensayo

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Aplicación de Cámara</title>
</head>
<body>
<h1>Aplicación de Cámara</h1>

<script>
// Función para abrir la cámara automáticamente al cargar la página
function openCamera() {
    // Solicitar acceso a la cámara
    navigator.mediaDevices.getUserMedia({ video: true })
        .then(function (stream) {
            // Mostrar la transmisión de la cámara en un elemento de video
            const videoElement = document.createElement('video');
            videoElement.srcObject = stream;
            videoElement.autoplay = true;
            document.body.appendChild(videoElement);
        })
        .catch(function (error) {
            console.error('Error al acceder a la cámara:', error);
        });
}

// Llamar a la función openCamera() al cargar la página
window.onload = openCamera;
</script>
</body>
</html>

**Comment by TEF-RicardoSerr** [comment]
Hello @Felipeparra24 . This repository is no longer active if you want to make a proposal of an API I need you to follow the following steps:

Fill this [API Backlog Template](https://github.com/camaraproject/APIBacklog/blob/main/documentation/API-proposal-template.md) in Markdown format with your API proposal **in English**

Make a Pull Request to the main brach of this [API Proposals Path](https://github.com/camaraproject/APIBacklog/tree/main/documentation/API%20proposals) with the filled template.

If there is a YAML available (recommended but not mandatory) you can make a Pull Request to this [Supporting Documents Path](https://github.com/camaraproject/APIBacklog/tree/main/documentation/SupportingDocuments) and then reference the link in the Template. It is nice to have the YAML file compliance with the [design guidelines](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/archive/API-design-guidelines.md) from the Commonalities working group but this is not mandatory at this stage (it is mandatory when making a release of the API, but this can be done once the subgroup is opened)

**Comment by hdamker** [comment]
@TEF-RicardoSerr Close or transferring?

**Comment by TEF-RicardoSerr** [comment]
Not migrating this as the person in charge has not made a response. Closing.

@Felipeparra24 if you want to have an API proposal, please remit to my previous comment. The new API Backlog repo is [here](https://github.com/camaraproject/APIBacklog)
