### ISSUE TITLE
Roaming Status API Proposal

### ISSUE THREAD

**Issue by eric-murray** [camaraproject/WorkingGroups#43]
A proposal for a Roaming Status API has been uploaded [here](https://github.com/camaraproject/WorkingGroups/blob/main/APIBacklog/documentation/Contributions/API%20Proposals/Roaming%20Status.md). Please add any comments you may have.

Unfortunately, I don't have permissions to add labels to this issue, so maybe somebody could do that for me.

**Comment by jordonezlucena** [comment]
@eric-murray: which 3rd parties could be the API consumer/caller? Maybe you could elaborate on this through a couple of concrete scenarios.

**Comment by Marcin-Jarzab** [comment]
Presented scenarios focus rather on B2C and are based on some security/fraud scenarios which limit API applicability.  
Nevertheless, access to ROAMING status requires user consent. Might be assumed the Roaming API will be used in a limited number of use-cases. 
External API “Capability Consumers” you mentioned: mobile phone insurance, content delivery, and device manufacturer.
In the “Notes” there are specified constraints valid in case of such “sensitive” information as roaming data exchange between operators.
 
Following questions about details of Roaming API to be clarified which mainly extends described functions and might cover other usage scenarios.
-         Device identification based on GPSI (MSISDN or External Identifier): should we clarify if SCEF/NEF implementations support the approach?
-         Support for a single device (Basic Roaming-API) or group of devices (Advanced Roaming API)?
-         Roaming history tracking per device or group of devices, which can be supported through the Notification mechanism. Is it crucial to have support for “history”?
 
Details related to activities in CAMARA or partnering “OPAG” be proposed for discussion in the long-term:
- The device status API proposed by DT (discussion on-going) includes the Roaming aspect.  
What about having a sync-up in the API-Group and discussing details?
- Roaming aspect is mentioned in the OPAG community to specify East-west APIs to support the management of federated “Operator Platforms”.

**Comment by eric-murray** [comment]
@Marcin-Jarzab Thanks for you comments

It is my understanding that CAMARA APIs do not explicitly handle the issue of user consent. Rather, the API would return some relevant error code if it was found that the API consumer did not have the correct rights to request roaming information for a given subscriber. But that would not prevent the request being made, so the API must be able to handle such requests. How this is handled is an internal issue for the API provider, but it is reasonable to assume that solutions exist for this and that obtaining the relevant consents is possible in at least some cases.

If your interface to the SCEF / NEF is the T8, then certainly querying by MSISDN or External Identifier is supported. To me, querying by MSISDN is more natural, but the general agreement is that either should be possible.

The T8 also supports identifying groups of subscribers via an External Group Identifier. I'm not convinced of the value of this for this use case, but it would appear to be possible.

I don't think the API itself should maintain a history of a subscriber's roaming history. The API consumer can do that themselves based on the notifications they receive if this is useful to them.

This API does indeed fall into the category of "Device Status". I understand that DT are going to fast-track a Device Status working group, and I will happily transfer this proposal to that WG when formed.

**Comment by eric-murray** [comment]
@MarkusKuemmerle has created a [DeviceStatus](https://github.com/camaraproject/DeviceStatus) WG, and I propose to close this issue here and move the Roaming Status API proposal to that WG as I believe this proposal sits nicely within that family. There is some ongoing discussion about the steps required to introduce a new API (see #53), so I will follow that process once defined. It is not even clear to me if I still need to fill in the [user story template](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Deliverables/Userstory-template.md), as no other API appears to have done that yet.

Let me know if there are any additional comments, otherwise I will close this issue.

**Comment by jordonezlucena** [comment]
Since the [DeviceStatus](https://github.com/camaraproject/DeviceStatus) WG is formally approved, I agree with you to move to the "Roaming Status API Proposal" to the actual WG. 
In relation to the guidelines for API onboarding and handling in CAMARA, we're still working in the draft, so processes captured are not binding yet. In response to your question on whether VF needs to fill in the [user story template](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Deliverables/Userstory-template.md), the answer is YES, but this is to be handled in the [DeviceStatus](https://github.com/camaraproject/DeviceStatus) WG.

**Comment by eric-murray** [comment]
@jordonezlucena 
Yes, agreed. But as we have a Backlog WG meeting tomorrow, let's wait until after that before closing this issue, in case there are any comments during the meeting itself.

**Comment by eric-murray** [comment]
As agreed, this issue will be closed in the Backlog WG and moved to the DeviceStatus WG
