### ISSUE TITLE
Review API readiness minimum criteria doc

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/WorkingGroups#5]
https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Working/API-Readiness-Checklist.md

**Comment by T-sm** [comment]
Template moved to https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Deliverables/API-exposure-reference-solution.docx

**Comment by Kevsy** [comment]
Created [PR 28] (https://github.com/camaraproject/WorkingGroups/pull/28)
- added security and privacy compliance criteria

**Comment by jordonezlucena** [comment]
@shilpa-padgaonkar, @T-sm: the "API-Readiness-Checklist.md" needs to be revisited, as the links captured there seem to be broken

**Comment by T-sm** [comment]
@jordonezlucena @shilpa-padgaonkar Thanks, José, the links have been updated. Also the document has been moved to [Working](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Working) directory.

**Comment by shilpa-padgaonkar** [comment]
PR #38 assigned to @Kevsy  
If merged, this issue can be closed.

**Comment by Kevsy** [comment]
[PR #38](https://github.com/camaraproject/WorkingGroups/pull/38) Merged
