### ISSUE TITLE
Clear, consistent and transparent process for API onboarding and handling

### ISSUE THREAD

**Issue by MarkusKuemmerle** [camaraproject/WorkingGroups#53]
We need a clear, consistent and transparent process for API onboarding and handling, that allows to track the situation of APIs from their introduction in the backlog to their final incorporation to the portfolio as technically/commercially available.

In my view, we need:
-	Clear indication on the necessary information participants need to provide to place a new API in the backlog (functional description, underlaying network/compute/IT capabilities, etc) so that the API can be understood and assessed
-	Criteria for approval at the SteerCo (main decision factors), so that WG and working space are created
-	Criteria for final inclusion in the portfolio (when we can say it is technically/commercially available)

The intention is not making the process more complicated or slow it down but add certainty and transparency, and hopefully speed it up and gain scale (grow quickly the API portfolio) by growing confidence in the participants.

Today, the information is not updated and it is difficult to get a snapshot of the situation out of the information in the GitHub. This is not a complain (in fact, I think we did not need it up to now) but a suggestion to improve.

**Comment by MarkusKuemmerle** [comment]
Working topics after first meeting with José (the issue was brought up by Telefonica):
+ Develop a requirements template which can be used by a partner/customer/OPAG to propose a new API (family) to CAMARA
+ Work out guidelines for the steering committee to decide on new Sub Projects. These guidelines have to be approved in the steering committee and included in the governance documents of the Project
+ Develop a checklist for "API is ready to use". Which deliverables are necessary for a complete release of an API?

**Comment by jordonezlucena** [comment]
The latest (and agreed) version of the guidelines is captured in the [PPT](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Contributions/20220818-CAMARA-API-onboarding-and-handling-process.pptx) located on documents/contributions. 
Next steps:
- A short version with main insights will be provided by end of this week (for approval at SteerCo meeting in 8th Sept)
- When approved, a .md file documenting the API onboarding and handling in CAMARA will be generated.

**Comment by MarkusKuemmerle** [comment]
Process proposal has been decided in the SteerCo at 8th of September. Follow up tasks:
+ Create Process description (MD format)
+ Reference it in ProjectStructureAndRoles.md
+ Create necessary templates (put inks in process description)
+ Define upload directory (put ink in process description)
+ Create API Backlog Table and sync it with API status table already in work in the Commonalities Working Group. Would 1 table for all be possible?

**Comment by MarkusKuemmerle** [comment]
See https://github.com/camaraproject/WorkingGroups/issues/31

**Comment by eric-murray** [comment]
Agreed to close
