### ISSUE TITLE
API proposal pipeline: from API backlog to SteerCo approval

### ISSUE THREAD

**Issue by jordonezlucena** [camaraproject/WorkingGroups#57]
The objective is to:
- Specify the steps that compose the pipeline. 
- Elaborate on a template with all the information that a partner/customer/OPAG should fill out when proposing a new API (family) to CAMARA. This template will be used as checklist to incorporate API in the backlog. 
- Work out guidelines for the steering committee to decide on new Sub Projects. These guidelines have to be approved in the steering committee and included in the governance documents of the Project.

**Comment by jordonezlucena** [comment]
The latest (and agreed) version of the guidelines is captured in the [PPT](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Contributions/20220818-CAMARA-API-onboarding-and-handling-process.pptx) located on documents/contributions. 
Next steps:
- A short version with main insights will be provided by end of this week (for approval at SteerCo meeting in 8th Sept)
- When approved, a .md file documenting the API onboarding and handling in CAMARA will be generated.

**Comment by MarkusKuemmerle** [comment]
See https://github.com/camaraproject/Governance/pull/65

It would be great to extend the API overview table to the implementation / deployment of APIs to have the whole lifecycle in.
The respective issue in the Commonalities Working Group has been closed, so the activity should be taken here.

**Comment by shilpa-padgaonkar** [comment]
@MarkusKuemmerle : Are you currently working on this topic?

**Comment by MarkusKuemmerle** [comment]
Yes, it's on my list

**Comment by MarkusKuemmerle** [comment]
https://github.com/camaraproject/WorkingGroups/pull/134

**Comment by jordonezlucena** [comment]
PR #134 closed. Awaiting PR #65 approval before closing issue
