### ISSUE TITLE
Template to maintain summary of Camara APIs

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/WorkingGroups#64]
This issue proposes the use of a document which can provide a summary and status for all the APIs in the Camara project.

**Comment by jordonezlucena** [comment]
Wouldn't be this topic already covered by [issue #12](https://github.com/camaraproject/WorkingGroups/issues/12), as per agreement captured in the [PPT](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Contributions/20220818-CAMARA-API-onboarding-and-handling-process.pptx) regarding latest version of guidelines?

**Comment by shilpa-padgaonkar** [comment]
we could maintain 2 docs:
1. Current active APIs and their status
2. API proposals and their status.

**Comment by Kevsy** [comment]
We may be able to have a single doc reflecting the status of each API per their state in the 'API pipeline' (per #57)

**Comment by jordonezlucena** [comment]
I generated [PR#77](https://github.com/camaraproject/WorkingGroups/pull/77)

**Comment by shilpa-padgaonkar** [comment]
Will be solved by PR #77
