### ISSUE TITLE
Testing principles doc

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/WorkingGroups#8]
Decide on the testing principles and tools for validation in telco networks

**Comment by jordonezlucena** [comment]
- Testing should consider the entire workflow -> from service API call to network configuration primitive, with all the steps in between (access control, workflow engine/transformation function, etc.)
- Testing aspects to be addressed: API syntax, semantics, functional and performance related aspects.

**Comment by jordonezlucena** [comment]
A couple of questions in relation to "Commonalities Core Documentation" project created on 4 May.
- Is the decision of defining a project to classify documentation also applicable to the rest of Working Groups?
- How to align this project with the **/documentation** directory? In the project, we classify the documentation into "to do", "in progress" and "reviewed"; in the **/documentation** directory, we have "contributions", "deliverables" and "working".

**Comment by shilpa-padgaonkar** [comment]
Marking issue as stale and closing. This will be reopened and worked on, once test cases contribution for QoD has been accepted.
