### ISSUE TITLE
Issues, branches, pull requests - cleaning up "API Backlog Working Group"

### ISSUE THREAD

**Issue by MarkusKuemmerle** [camaraproject/WorkingGroups#88]
Dear "leading responsibles" for the CAMARA Sub Projects and Working Groups,

to have a clear view in which status each deliverable of CAMARA is we've defined a process "Changes and contributions to CAMARA".
The description of that process you can find in the https://github.com/camaraproject/Governance/blob/main/ProjectStructureAndRoles.md in the respective chapter.
That is the result of a discussion which has been started in the steering committee some weeks ago, I hope you can remember.

Now I would like to ask you to clean up "your" repository so that all issues, pull requests and files follow this process. In detail that means:
- Please check that for each branch and each pull request there is an issue (and both are linked vice-versa)
- Please check that issues, branches and pull requests are handled according the process
- Please eliminate all folders like "Contributions", "Working", "Deliverables". We don't track the status of files by means of subdirectories. That was the first (bad) approach.
- Please check that the folder structure follows this (for Sub Projects):
  /code/API_code
  /code/API_definitions
  /documentation/API_documentation
  /documentation/MeetingMinutes
  /documentation/SupportingDocuments
- Please check that the folder structure follows this (for Working Groups):
  /documentation/MeetingMinutes
  /documentation/SupportingDocuments
- Please check that every file outside /documentation/MeetingMinutes and outside /documentation/SupportingDocuments is a (final) deliverable of CAMARA.
   Files that have been (intermediate) contributions should either be added to the respective issue or moved to the /documentation/SupportingDocuments subdirectory.

**Comment by jordonezlucena** [comment]
@MarkusKuemmerle: I've updated it without PR (apologies). Could you please double check and validate if everything is compliant with the guidelines agreed in Governance?

**Comment by MarkusKuemmerle** [comment]
@jordonezlucena: Are there issues for the 2 open pull requests?

**Comment by jordonezlucena** [comment]
> @jordonezlucena: Are there issues for the 2 open pull requests?

The PRs open are tagged with 'Commonalities' tag, and therefore out of scope of API Backlog WG. Nonetheless, yes, there are issues associated to individual PRs.

**Comment by MarkusKuemmerle** [comment]
OK, then this issue can be closed. Clean up is done :-)

**Comment by jordonezlucena** [comment]
Following clean-up, this issue is closed
