### ISSUE TITLE
Authentication and authorization concept doc

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/WorkingGroups#9]

**Comment by jordonezlucena** [comment]
It is assumed that there is a need to have an 'exposure function / API gateway' mediating between API consumer (aka API invoker, within 3rd party domain) and API producer (within operator domain). This function is in charge of implementing necessary access control (AuthN/Z), and providing service API registry and discovery capabilities. 

Some requirements in relation to AuthN/Z here: 
-Mutual authentication between the API consumer and the 'exposure function / API GW ' shall be supported.
-The transport messages exchanged between the API consumer and the 'exposure function / API provider' shall be integrity and confidentiality protected.
- Privacy of the UE shall be protected in the messages exchanged between the API consumer and the 'exposure function / API provider'.
- The 'exposure function / API provider' shall determine whether API consumer is authorised to access service API.

Possible solutions for Auth/Z:
1) Using TLS-PSK -> assumes that both the API consumer and API producer are pre-provisioned with certificates. 
2) Using PKI 
3) Using TLS with OAuth 2.0 token.

All of these solutions are covered with CAPIF framework, which is proposed as reference solution for 'exposure function / API GW) in CAMARA. For further details, see issue #1
