### ISSUE TITLE
Dealing with multiple API related artifacts of the same type and conformance to APIs

### ISSUE THREAD

**Issue by lbertz02** [camaraproject/WorkingGroups#99]
The following types of artifacts are possible for APIs.

‘code’ contribution types, outside of documentation, include but are not limited to:
- API – Governed through API processes
- Server Implementations – Code that implements the API’s server portion, i.e., provides the API to clients.
- Client Implementations – Code that uses an API and may provide examples. It includes general housekeeping, basic, and convenience functions.
- Examples – Code showing how to use / implement an API. It is NOT a complete Client or Server implementation. Clients MAY have example code with them that is part of their project.
- Test Cases (code) – Code that is independent or uses a test framework to verify a Client and/or Server implementations. It may provide complete or partial test coverage for an API.

There may be type overlap in the code and that is fine. However, all contributions MUST comply with CAMARA policies.

For an API a page should be created (may be one page for many, one per workgroup, etc.) with links to CAMARA and external project locations for the contributions to CAMARA as well as projects outside of CAMARA that implement related artifacts like those defined above.

If the community agrees upon Test Cases or Implementations that can be used for validating API compatibility, they should be noted. NOTE - to claim full compatibility with an API, it is best practice to use Test Code even when a Client or Server implementation is used and, further, following a Verification Specification (which may vary by API or over time) is best. Use of tags can help define specific versions Test Code certifies as well. The objective would be to make it easy to find software to validate compatibility for implementations.

If projects want to claim some level of compatibility, we should define a simple process and how it may be documented so all parties agree to the claims.

**Comment by gmuratk** [comment]
We (Lyle & Murat) would like to share some recommendations with the team at the next meeting. 
[CAMARA WG Issue 99-v2.pptx](https://github.com/camaraproject/WorkingGroups/files/10448170/CAMARA.WG.Issue.99-v2.pptx)

**Comment by gmuratk** [comment]
We (Lyle & Murat) would like to share some recommendations with the team at the next meeting.
[CAMARA - Commonalities WG - Issue 99.pdf](https://github.com/camaraproject/WorkingGroups/files/10451282/CAMARA.-.Commonalities.WG.-.Issue.99.pdf)

**Comment by gmuratk** [comment]
Proposing to close Issue #99 based on the following updates​

1. Reference Implementations are now moved to their respective subprojects/repositories with links from API_FAMILY repo Note: QualityOnDemand with [Issue #52 ](https://github.com/camaraproject/QualityOnDemand/issues/52)now closed)​
2. [PR #123 ](https://github.com/camaraproject/WorkingGroups/pull/123)intends to address versioning guidelines​
3. Testing/Conformance requirements for each subproject will be handled by respective groups as the need arise.

[CAMARA - Commonalities WG - Issue 99 - Update - 03FEB2023.pdf](https://github.com/camaraproject/WorkingGroups/files/10580052/CAMARA.-.Commonalities.WG.-.Issue.99.-.Update.-.03FEB2023.pdf)

**Comment by shilpa-padgaonkar** [comment]
@gmuratk Thnx for the feedback. Will close the issue.
